version: "3.8"

services:
    express-api:
        container_name: express-restapi
        image: node:lts-alpine
        working_dir: /app
        ports:
            - 8081:8081
        volumes:
            - .:/app
        # entrypoint: ['npm', '']
        tty: true
        env_file:
          - ./.env
        # command: nodemon app.js